version: '3.8'
services:

  adminer:
    container_name: audio_adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  db-mysql:
    container_name: audio_db
    image: mysql:8.0
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: 'audio'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'audio'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'acmesystemsaudio'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'acmesystems'
    ports:
      - '3306:3306'
      - '33060:33060'
    expose:
      - '3306'
      - '33060'
    volumes:
      - ./data/db/mysql:/var/lib/mysql
